#!/bin/sh

[ -z "$DIR" ] && readonly DIR="$HOME/.gitman"
[ -z "$LIST" ] && readonly LIST="$DIR/list"

myeval() {
    [ -n "$verbose" ] && echo "$*" >&2
    [ -n "$dryrun" ]  || eval "$*"
}

usage() {
	cat <<-EOT
		usage: $(basename $0) [-nv] <command> <repository> [<args>]

		Commands:
		   add
		   update
		   remove
		   list
		   help
	EOT
}

hash() {
	if which md5sum > /dev/null; then
		echo "$*" | md5sum | cut -d' ' -f1
	elif which md5 > /dev/null; then
		echo "$*" | md5
	else
		basename "$*"
	fi
}

is_added_repository() {
	[ -n "$(awk '$1=="'"$*"'"' "$LIST")" ]
}

while getopts "nv" opt; do
    case $opt in
        n) dryrun=1;;
        v) verbose=1;;
    esac
done

shift $(( $OPTIND - 1 ))
command=$1

mkdir -p "$DIR" && cd "$DIR"
[ ! -f "$LIST" ] && touch "$LIST"

case $command in
	add )
		shift
		repository=$1

		shift
		[ $# -eq 0 ] && usage && exit 1
		args=$*

		# check $LIST
		if is_added_repository $repository; then
			echo "$repository is already added." 1>&2
			exit 1
		fi

		# add
		dir=$(hash "$repository")
		[ -d "$dir" ] \
			&& myeval "(cd \"$dir\" && git pull && $args)" \
			|| myeval "git clone --depth 1 ${repository} \"$dir\" && (cd \"$dir\" && $args)"

		# add $repository to $LIST
		[ $? -eq 0 ] && echo "$repository $args" >> "$LIST"
		;;
	update )
		(
		IFS='
		'
		for line in $(cat "$LIST"); do
			repository=$(echo "$line" | cut -d' ' -f1)
			args=$(echo "$line" | cut -d' ' -f2-)

			# check $LIST
			if ! is_added_repository "$repository"; then
				echo "$repository is not added." 1>&2
				exit 1
			fi

			# update
			dir=$(hash "$repository")
			echo "$repository $args"
			myeval "(cd \"$dir\" && git pull && $args)" || exit 1
		done
		)
		;;
	remove )
		shift
		repository=$1
		shift
		args=$*

		# check $LIST
		if ! is_added_repository "$repository"; then
			echo "$repository is not added." 1>&2
			exit 1
		fi

		# remove
		dir=$(hash "$repository")
		if [ -n "$args" ]; then
			myeval "(cd \"$dir\" && $args) && rm -rf \"$dir\"" || exit 1
		else
			myeval "rm -rf \"$dir\"" || exit 1
		fi

		# remove $repository from list
		awk '$1!="'"$repository"'" {print}' "$LIST" > "$LIST.tmp" && mv "$LIST.tmp" "$LIST"
		;;
	list )
		(
		IFS='
		'
		for line in $(cat "$LIST"); do
			repository=$(echo "$line" | cut -d' ' -f1)
			args=$(echo "$line" | cut -d' ' -f2-)
			echo "$DIR/$(hash "$repository")" "$repository" $args
		done
		)
		;;
	help )
		usage && exit 0
		;;
	* )
		usage && exit 1
		;;
esac
